# Generated by Django 4.1 on 2022-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_car_alter_greeting_id_alter_greeting_when_violation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
