# Generated by Django 4.1 on 2022-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_violation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.CharField(default='ركون خاطئ', max_length=50),
        ),
    ]
